### ISSUE TITLE
Setting the position of notes in the ini file

### ISSUE THREAD

**Issue by northpole-pl** [Cimbali/pympress#122]
It would be very convenient to save the position of notes in the ini file. Maybe it is possible to set it, but I haven't found a way.

If there was an option to save the current program settings, it would make it much more comfortable to use pympress.

**Comment by Cimbali** [comment]
Hi @northpole-pl, settings should be saved automatically on program exit.

I’m not sure what you mean by the position of the notes though?

**Comment by Cimbali** [comment]
If you mean flipping them (notes left of slide or reversed), or setting one panel above of the other, etc., you should try playing with the entries of the `layout` section in your config file.
Here are a couple examples of layouts, with `Cu` the current slide, `No` the notes half of the slide, `Nx` the next slide:


- All-horizontal layout:

      +----+----+----+
      | Cu | No | Nx |
      +----+----+----+

  Setting:

      notes = {"children": ["current", "notes", "next"], "proportions": [0.33, 0.33, 0.33], "orientation": "horizontal", "resizeable": true}

- All-vertical layout:

      +----+
      | Cu |
      +----+
      | No |
      +----+
      | Nx |
      +----+

  Setting:

      notes = {"children": ["current", "notes", "next"], "proportions": [0.33, 0.33, 0.33], "orientation": "vertical", "resizeable": true}

- Vertical layout with horizontally divided top pane:

      +----+----+
      | Cu | No |
      +----+----+
      |    Nx   |
      +---------+

  Setting:

      notes = {"children": [
					{"children": ["current", "notes"], "proportions": [0.5, 0.5], "orientation": "horizontal", "resizeable": true},
					"next"
				], "proportions": [0.5, 0.5], "orientation": "vertical", "resizeable": true}


- Horizontal layout with horizontally divided right pane:

      +----+----+
      |    | Nx |
      + Cu +----+
      |    | No |
      +---------+

  Setting:

      notes = {"children": [
					"current",
					{"children": ["next", "notes"], "proportions": [0.5, 0.5], "orientation": "vertical", "resizeable": true}
				], "proportions": [0.5, 0.5], "orientation": "horizontal", "resizeable": true}

And so on. You can play with the items, their nesting, their order, and the orientation in which a set of widgets appears.

For each entry the widgets (strings that are leaves of "children" nodes in this representation) must be:

- for `notes`: "current", "notes", "next"
- for `plain`: "current", "next" and "annotations" (the annotations widget is toggled with the `A` key by default)
- for `highilight`: same as `plain` with "highlight" instead of "current"

A few further remarks:

-  If you set "resizeable" to `false`, the panes won’t be resizeable dynamically with a handle in the middle
- "proportions" are normalized, and saved on exit if you resize panes during the execution. If you set them to `4` and `1`, the panes will be `4 / (4 + 1) = 20%` and `1 / (4 + 1) = 100%`, so the ini will contain something like `0.2` and `0.8` after executing pympress.

The idea to make this modifiable without editing the ini file has been around for a while (see #83) but I’m not sure how to make that easy to use. Any suggestions welcome.

**Comment by northpole-pl** [comment]
Hi @Cimbali, Thank you for the examples of settings in the ini file.
But I have a problem with setting the position of notes that are saved in a pdf file. I have a lot of presentations with notes saved on the left (in pdf). When I turn on the presentation I have to switch in Presentation/Notes position/Left menu every time. I wanted to save these settings in the ini file.
Is it currently possible?

**Comment by Cimbali** [comment]
Ah I get it now ! it’s where your notes are stored inside the PDF. We don’t have a preference for that at the moment, we detect notes automatically from the slides’ aspect ratio, so we can detect only horizontal or vertical arrangements. They default to right or bottom respectively:

https://github.com/Cimbali/pympress/blob/60da16b766208087b41ec6c322b9d12e68577f45/pympress/document.py#L655-L664

I suppose I could add a preference for that, or remember the last arrangement (probably only left v right for horizontal and top v bottom for vertical).

Note that if you open pympress from the command line, you can also directly override the position with `pympress --notes left <file.pdf>` or `pympress -nl <file.pdf>`

**Comment by northpole-pl** [comment]
> I suppose I could add a preference for that, or remember the last arrangement (probably only left v right for horizontal and top v bottom for vertical).
It would be useful

>Note that if you open pympress from the command line, you can also directly override the position with pympress --notes left <file.pdf> or pympress -nl <file.pdf>
Thanks, actually, it solves my problem.

**Comment by Cimbali** [comment]
We’re now remembering the last position used (separately for horizontal and vertical positions). Still guessing the best we can whether there are notes, and whether they are positioned vertically or horizontally.
