### ISSUE TITLE
Illegal hardware instructions

### ISSUE THREAD

**Issue by algon-ns** [Cimbali/pympress#127]
# Environment
macOS Catalina 10.15
python 3.7.5 og 2.7.17

# Pympress
version 1.5.1
python3 -m pip install pympress

# Steps to reproduce
in term2:
xxxx - % _pympress_

# Problem
zsh: illegal hardware instruction  pympress

can't find a log-file at any expected places

![Skærmbillede 2019-12-07 kl  12 12 02](https://user-images.githubusercontent.com/58687687/70432038-98347e80-1a7e-11ea-9a0c-6854da1e863f.png)

**Comment by Cimbali** [comment]
Hi @algon-ns and thanks for reporting this bug. It seems the SIGILL is caused by `libcairo`, can you show how that was installed? Could you also reinstall it from source, to see if recompiling it fixes the issue? For example with:

    brew install --build-from-source --force

**Comment by algon-ns** [comment]
hi
Same problem, it compiled without any problems, but still get the "illegal hardware instruction"
I'll try to find the place in the source
mvh
Niels

**Comment by algon-ns** [comment]
Hi,
I reloaded my computer, so Catalina is totally without any weird addition.
I get the same problem.
I do have to confess, that my MacBook Pro is an elderly lady (Mid 2009), and the Catalina is not really supported on it, so I'll have to find something else, as You should trying til fix a proem running on an unsupported machine.

**Comment by Cimbali** [comment]
As far as I can tell the problem is in libcairo. Maybe it’s trying to use instructions that are meant for newer hardware than yours?

Signal 4 is illegal instruction (“SIGILL”), and you have the address of that instruction in the library, given on the first line of the stack trace: `0x105c72de5` which is 24 bytes (or 24 instructions possibly, not entirely sure) inside the `_cairo_rectangle_intersect` function. If you have a disassembler (e.g. objdump which you can install as `brew install binutils`) you could have a look at it, finding the right address in the output of objdump. Maybe something like:

    objdump -d /<path to libcairo here>/libcairo.2.dylib --start-address=0x105c72d25

You could also use gdb if that’s installed with:

     gdb -batch -ex 'file /<path to libcairo here>/libcairo.2.dylib' -ex 'disassemble _cairo_rectangle_intersect'

[This stackoverflow post contains more solutions.](https://stackoverflow.com/questions/22769246/how-to-disassemble-one-single-function-using-objdump)
