### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by eddrog** [Cimbali/pympress#148]
# Enhancement
Selectable dark theme. It would increase the contrast.

**Comment by Cimbali** [comment]
As a Gtk application, pympress uses the Gtk theme. I think that rather than rolling our own themes, users should look into finding a theme they like and applying it either to their whole system or just to pympress. You can of course report if some things don’t seem to work well with any given theme.

For example starting with a dark theme (supposing it is installed) from the command line:

    GTK_THEME=Greybird-Geeko-Dark pympress

There is information online about [how to change .desktop files and add command line aliases](https://askubuntu.com/questions/78088/can-i-apply-a-different-gtk3-theme-from-the-main-one-to-an-individual-applicatio) to make the change stick to a single program.

**Comment by eddrog** [comment]
Hm. How to do this on windows?

**Comment by eddrog** [comment]
Got it
