### ISSUE TITLE
[OSX] AttributeError: 'module' object has no attribute 'bindtextdomain'

### ISSUE THREAD

**Issue by brianmay** [Cimbali/pympress#15]
Hello,

Apparently this has been tested on Mac (assuming you mean OSX?), however I am not able to get past this error:

```
$ pympress            
2017-02-24 10:17:08.800 python2.7[49410:3172507] *** WARNING: Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead. 
Traceback (most recent call last):
  File "/tmp/virtual/bin/pympress", line 7, in <module>
    from pympress.__main__ import main
  File "/tmp/virtual/lib/python2.7/site-packages/pympress/__main__.py", line 46, in <module>
    locale.bindtextdomain('pympress', pympress.util.get_resource_path('share', 'locale'))
AttributeError: 'module' object has no attribute 'bindtextdomain'
```

If I try:

```
$ python
Python 2.7.13 (default, Feb 24 2017, 10:13:58) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import locale
>>> locale.bindtextdomain
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'bindtextdomain'
>>>
```

I am a bit puzzled at this point, I thought that was a standard Python feature.

Regards

**Comment by Cimbali** [comment]
Yeah some of the locale things are not really done in a portable way (there is already a special case for windows...). I don't have a Mac myself so I can't really test regularly, I might have broken something inadvertently.

Basically the problem here is that Gtk relies on the locale domain being set in the C gettext library, which the gettext module doesn't do -- which is why we do it through the locale module, which exposes the C gettext library's functions directly. A binding that doesn't work on your platform apparently.

The standard Python feature as you say, would be to do bind the text domain with the gettext module, but this results in only half the strings being translated (those dynamically used from the python code, but not those loaded by the Gtk widgets).

Let me go look for a workaround.

**Comment by Cimbali** [comment]
@brianmay Is there a `libintl.dylib` ou your system? Does importing that in python with cdll allow to call bindtextdomain? something like:

    import ctypes
    lib = ctypes.cdll.LoadLibrary('libintl.dylib')
    lib.bindtextdomain('test', '/usr/share/locale/')

**Comment by brianmay** [comment]
```
>>> import ctypes
>>> lib = ctypes.cdll.LoadLibrary('libintl.dylib')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/brianmay/.pyenv/versions/2.7.13/lib/python2.7/ctypes/__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "/Users/brianmay/.pyenv/versions/2.7.13/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(libintl.dylib, 6): image not found
```

Looks like on my system I have a ``/usr/local/Cellar/gettext/0.19.8.1/lib/libintl.dylib``.

Ok, this helps.

```
export LD_LIBRARY_PATH=/usr/local/Cellar/gettext/0.19.8.1/lib/
```

Now:

```
>>> import ctypes
>>> lib = ctypes.cdll.LoadLibrary('libintl.dylib')
>>> lib.bindtextdomain('test', '/usr/share/locale/')
1490168128
```

Ok, that looks better so far. Will try pympress again.

**Comment by brianmay** [comment]
pympress still generates the same error.

**Comment by Cimbali** [comment]
If you check out the `fix-osx-i18n` branch, this should be fixed (not crash anymore).
You can do this with (adding you favourite options, and maybe --upgrade and --force-reinstall)

    pip install git+https://github.com/Cimbali/pympress.git@fix-osx-i18n

What's more, if `libintl.dylib` is in your library path and you set `LANG` to `de_DE.utf-8` or `fr_FR.utf-8`, pympress should run in German or French respectively.

**Comment by brianmay** [comment]
It works!

Thanks for your help.
