### ISSUE TITLE
Problem installing: "Could not update environment variable 'Path' " 

### ISSUE THREAD

**Issue by Serafin-Frache** [Cimbali/pympress#167]
### Environment
- Windows 10 

### Pympress
- version 1.5.3
- Installation method:  pympress-v1.5.3-x86_64.msi

### Problem
Currently using 1.5.2. I have been using previous versions of pympress without any issue, always installing in the same way. Installation process stops around 60% and the following message appears: "Could not update environment variable 'Path'. Verify that you have sufficient privileges to modify environment variables. "

### Steps to reproduce
Installing 'pympress-v1.5.3-x86_64.msi'.

I have been looking for a solution, installing also as Admin, but the issue still arises.
Many thanks in advance.

**Comment by raphaelquast** [comment]
same here... but the program works anyways if you ignore the error 😄 
I guess it's just for file-type-associations?

**Comment by Cimbali** [comment]
It’s to start pympress from the command line, which is not the most common way of using pympress on Windows. I have to look into it but haven’t had time yet.

In particular I’m not sure why the installer package allows an option that is modifying the path (which we use) without asking for privileges. We should probably ask for privileges too.

**Comment by raphaelquast** [comment]
how about simply adding an option
- [ ] add pympress to path? (requires admin privileges)

that is disabled by default on windows?
(this would serve most windows users and keep the option for experts that know how to handle this)

**Comment by Cimbali** [comment]
That’s a good way of doing it @raphaelquast but I didn’t write the package installer, pympress uses the python installer. Maybe the installer we use allows that, or maybe we can migrate to nsys or some other installer if it’s any better.

**Comment by Cimbali** [comment]
So apparently pynsist already handles this by modifying the user’s PATH variable instead of the global PATH variable, when installing for a single user and not for aller users (i.e. when installing without privileges). Specifically it seems to be a different registry key:

https://github.com/takluyver/pynsist/blob/7319915442550c74526d2f0a5e9c8e457bcd8899/nsist/_system_path.py#L136-L145

On the other hand, in cx_Freeze the Path option is prepended with `*` only if `all_users` is set to True: 

https://github.com/marcelotduarte/cx_Freeze/blob/c8c125b384252ba2da1a818d7f54d059e8dcc75a/cx_Freeze/windist.py#L42-L45

This in turn means that the user’s, not the system’s, environment variable should be modified:

https://docs.microsoft.com/en-us/windows/win32/msi/environment-table

After taking apart the current installer with lessmsi, it seems we do request the global path (which means we set `all_users=True` at some point?)

**Comment by Cimbali** [comment]
Can you try out the [1.6.0-beta4](https://github.com/Cimbali/pympress/releases/tag/v1.6.0-beta4) installer ? The `*` prefix seems absent from the MSI when inspecting with lessmsi, so this issue should be fixed now.

**Comment by Serafin-Frache** [comment]
I tried it, and it worked perfectly fine. Thanks for your time and work!

**Comment by Serafin-Frache** [comment]
Unfortunately, now I have a problem with this 1.6.0-beta4 version. The slides appear cropped, as in this issue: 
https://github.com/Cimbali/pympress/issues/181#issuecomment-750663780
I noticed "About" still said my previous version 1.5.3
I rolled back to that version, and again, this cropping issue  persists. 
Do you know how can I get a working version? 
Many thanks in advance.

**Comment by Cimbali** [comment]
Just to confirm, you’re running on Windows @Serafin-Frache ?

- I did not update the version in the about dialog for the betas
- If you roll back you might need to delete the config file to completely reset pympress. I’d be surprised if that affects the slide cropping though, but that issue had config files issues too, so maybe that’s what happens ?

**Comment by Serafin-Frache** [comment]
Hi there,
Yes, I am running it on Windows, should have mentioned that, sorry. 
By removing the config file, do you mean "pympress.conf", "lib\pympress\config.pyc" or the ones under the python and g-lib folder?
When I rolled back I uninstalled pympress from Control Panel and then installed it again with no luck.
Thanks.

**Comment by Cimbali** [comment]
I mean the one that’s mentioned in the about dialog. It should be `%APPDATA%\pympress.ini`

**Comment by Cimbali** [comment]
Let’s close this issue and track the cropping problems on #181.
