### ISSUE TITLE
Disable hardware acceleration with VLC in pympress?

### ISSUE THREAD

**Issue by WillemKauf** [Cimbali/pympress#200]
### Environment
- Fedora 34
- Python 3.9.5

### Pympress
- 1.6.1
- DNF

### Expected behaviour
Present embedded videos generated with ffmpeg (libx264 .mp4s) in a beamer presentation using multimedia package, autostarting and looping in presentation using no hardware acceleration (it seems that VDPAU and planar YUV 4:2:0 don't play well for some reason.)

### Steps to reproduce
  \movie[height=5in, width=\textwidth,autostart, loop, poster]{}{/mnt/school work/results/1DEuler/shu_osher/subplot.mp4}

### Problem
Movies don't autostart and they don't loop. I get an error with VLC encoders, which is fine, but I'd like to be able to set the default VLC hardware acceleration option to "disabled", which doesn't seem to happen even after I set the option in VLC.
[00007f3e90014760] main filter error: Failed to create video converter
[00007f3e840081e0] main filter error: Failed to create video converter
[00007f3e94092c30] vdpau_avcodec generic error: Xlib is required for VDPAU
[00007f3e8c07ff30] vdpau_avcodec generic error: Xlib is required for VDPAU

What is reported in pympress.log?\*
Nothing relevant to the VLC encoding issue, but the terminal output says it all.
Does the problem still happen if you remove your config file?\*
Yes. How can I force pympress's VLC to disable hardware acceleration?

**Comment by Cimbali** [comment]
`libvlc` seems to ignore the user configuration file by design. If you want to pass some configuration to pympress’ VLC backend, you need to do it by modifying the `init_options` configuration option under `[vlc]` in `~/.config/pympress`. The full list of possible options is obtained by running `vlc --full-help`.

However, it seems that the option you might want to control in order to disable VDPAU and remove the error messages is `--avcodec-hw`, which is intentionally dropped when vlc is embedded (as we need to do to show the video in a slide):

https://github.com/videolan/vlc-3.0/blob/738da6c2737d2da93b24b7cce47944d45d10d8d3/lib/media_player.c#L1196-L1208

The error message you’re seeing is benign as VLC by itself falls back on another decoding for the avcodec. It is due to the `--no-xlib` flag we use, however if we remove it there are the only 2 options:

- Either we initialize threads with `ctypes.CDLL('libX11.so').XInitThreads()` − this causes a segfault.
- Or we keep threads uninitialized − that would make little sense and replaces your error messages with the following:
  ```
  ../include/vlc_xlib.h:46:vlc_xlib_init: Xlib not initialized for threads.
  This process is probably using LibVLC incorrectly.
  Pass "--no-xlib" to libvlc_new() to fix this.
  [00007f4920001730] glx gl error: Xlib not initialized for threads
  ```

Of course if you have other suggestions I’m open to them, but I think the best way forward is to make the GStreamer integration more stable and then use that instead − the goal there is to use a Gtk sink widget rather than the window handle mechanism used now.

---
About movies not autostarting and not looping: that’s unrelated, and tracked in #71 − basically the Poppler backend did not provide the information until very recently. It’s still unclear whether the changes to Poppler are available in the Gobject introspections. I’ll happily accept any PRs on this.

**Comment by Cimbali** [comment]
But do you actually have video playback issues that seem linked to the HW acceleration ? If so, can you describe those ?

**Comment by WillemKauf** [comment]
No, no issues with playback related to HW acceleration. Just thought that the autostart and loop functions not working were related to my avcodec issue.
