### ISSUE TITLE
allow mouse clicks to unpause and advance slides

### ISSUE THREAD

**Issue by ousia** [Cimbali/pympress#224]
@Cimbali,

I wonder whether the mouse primary button could be made optional to start time and advance slides.

I mean the same way as the space bar is used to do the same.

Many thanks for your help.

**Comment by Cimbali** [comment]
This is similar to #179, where the semantics aren’t clear. Currently, clicking is only activating buttons or links. You can already use the mouse on the “Previous” and “Next” buttons (tick “Big buttons” in the “Presentation” menu to have the buttons displayed).

For example, if you miss-click just next to a link, going to the next slide isn’t what you want, and this can happen regularly − especially with the tiny beamer navigation links, or on touch screens.

Surely this can be made optional, but even then, should a click anywhere advance to the next page?
- On the content window: Anywhere? Only on non-links?
- On the presenter window: On the slide except for links? On the rest of the window except for menus / buttons? etc.

**Comment by ousia** [comment]
In my personal opinion, a click anywhere in the page should advance to the next page, no matter where in the page.

This would be the easiest to implement, too.

**Comment by Cimbali** [comment]
For reference, I checked what Libreoffice does − they have a distinct “background” part to their presenter setup, and that’s the only part that advances slides when clicked, i.e. the slight grey part:

![image](https://user-images.githubusercontent.com/6126377/140662684-0eb8c015-7192-4854-8f69-32adca791173.png)

Nothing happens when you actually click *on* the slides, which may help with links as mentioned.

**Comment by ousia** [comment]
Many thanks for showing _LibreOffice_, @Cimbali.

This is also an option. On second thought, having buttons make more sense here for the vast majority of users.

So, closing the issue myself.
