### ISSUE TITLE
First slide in presenter mode. 

### ISSUE THREAD

**Issue by AndreaDiPietro92** [Cimbali/pympress#294]
**Describe the bug**
When I open a PDF with notes, the first page is not viewed on the Presenter Windowns (just the first page of the presentation)

**To Reproduce**
1. Open a PDF with notes
2. Watch on the top right corner of the notes
3. See error

**Expected behavior**
I should see the current page of the presentation.
**Screenshots**
![image](https://github.com/Cimbali/pympress/assets/36949583/1a725621-233d-4fb4-9789-2e9ed805f6c7)
and then 
![image](https://github.com/Cimbali/pympress/assets/36949583/dc634c18-f603-4e8f-8eb4-21353c6bae13)

**Environment (please complete the following information):**
 - OS: Kubuntu 23.04
 - Python version: 3.11.2
 - Pympress version: 1.7.1
 - Installation method: apt install

**Comment by Cimbali** [comment]
IIUC, you’re saying the top-right corner of the first notes slide should contain (a preview of) the first slide but it doesn’t.

If so, that’s unlikely to be caused by pympress and likely more a PDF issue. Also, the “Current slide” part of the presenter window shows the current slide correctly, so maybe you don’t even need to have the tiny preview in the Notes’ slide corner?

In any case, can you share the PDF? What does it look like when you open it with a regular PDF viewer, does the corner-preview show correctly then? Where are the notes slides located, on the top half of the pages? right half? separate pages?

**Comment by AndreaDiPietro92** [comment]
Exactly. This is the PDF with notes  (created with options `\setbeameroption{show notes on second screen=right}`)
[Presentazione-NOTE.pdf](https://github.com/Cimbali/pympress/files/12182811/Presentazione-NOTE.pdf)

**Comment by Cimbali** [comment]
So as I suspected, this is definitely a latex error, not a pympress error. You could try creating the smallest possible beamer source that produces this effect and ask on [LaTeX Stack Exchange](https://tex.stackexchange.com/), they seem to have similar questions e.g. [this one](https://tex.stackexchange.com/questions/33051/note-page-showing-the-next-frame/) and [this other one](https://tex.stackexchange.com/questions/229437/command-showing-note-page-of-the-next-frame).
