### ISSUE TITLE
[python2] TypeError: string indices must be integers

### ISSUE THREAD

**Issue by polaksta** [Cimbali/pympress#31]
Today i have installed new version and when I try to execute the code ...

$ ./pympress
Traceback (most recent call last):
  File "./pympress", line 11, in <module>
    load_entry_point('pympress==1.0.3', 'gui_scripts', 'pympress')()
  File "/home/polak/.local/lib/python2.7/site-packages/pympress/__main__.py", line 116, in main
    ui = pympress.ui.UI(ett, name)
  File "/home/polak/.local/lib/python2.7/site-packages/pympress/ui.py", line 329, in __init__
    self.make_pwin()
  File "/home/polak/.local/lib/python2.7/site-packages/pympress/ui.py", line 645, in make_pwin
    self.rearrange_p_layout(self.notes_layout if self.notes_mode else self.plain_layout)
  File "/home/polak/.local/lib/python2.7/site-packages/pympress/ui.py", line 577, in rearrange_p_layout
    w = Gtk.Box.new(getattr(Gtk.Orientation, w_desc['orientation'].upper()), 5)
TypeError: string indices must be integers

**Comment by polaksta** [comment]
This error is seen when I use python2. With python3 it is OK

**Comment by FriedrichFroebel** [comment]
I just added some additional logging to the method which produces this error: In line 546, I added `print(type(w_desc))` and `print(w_desc)` before line 577.

Output for `python -m pympress` running the latest master with Python 2.7:

> <type 'dict'>
> <type 'dict'>
> <type 'unicode'>
> current
> current

Output for `python3 -m pympress` running the latest master with Python 3.5 (I quit the application when the file chooser was shown):

> <class 'dict'>
> <class 'dict'>
> <class 'str'>
> current
> <class 'str'>
> annotations
> <class 'str'>
> next

Seems like the if condition in line 547 needs to be extended using something like

```python
if type(w_desc) is str or type(w_desc) is unicode:
    w = self.placeable_widgets[w_desc]
```

The problem is that Python 3 does not have the `unicode` type, so this part of the code probably needs to be rewritten to be able to support both Python 2 and Python 3:

```python
is_string = False
try:
    is_string = type(w_desc) is unicode
except NameError:
    is_string = type(w_desc) is str

if is_string:
    w = self.placeable_widgets[w_desc]
```

**Comment by lucjaulmes** [comment]
Done! Thanks for reporting. Should work OK even on python2 now, as far as I can tell.

**Comment by Cimbali** [comment]
Done! Thanks for reporting. Should work OK even on python2 now, as far as I can tell.

**Comment by polaksta** [comment]
You are fast as lightning :-)
