### ISSUE TITLE
Making annotations

### ISSUE THREAD

**Issue by jeslago** [Cimbali/pympress#37]
How is the annotations feature supposed to work? I can't add annotations.

I have tried the solution given here:

https://tex.stackexchange.com/questions/21777/is-there-a-nice-solution-to-get-a-presenter-mode-for-latex-presentations

But I cannot make it work. Any suggestions/advice?

**Comment by Cimbali** [comment]
I'm afraid that more details than you "cannot make it work" is needed to help you. What are you doing? What are you trying to achieve? What's the expected outcome? What's happening instead of what you are expecting?

In particular, try to compile slides with notes on second screen enabled, and with `\note{text here}` commands throughout your document. Are the pages in the pdf document twice as wide as the expected aspect ratio? Does the text you put inside the `\note{}` commands appear?
