### ISSUE TITLE
"Blue" is not translated into Polish

### ISSUE THREAD

**Issue by polaksta** [Cimbali/pympress#49]
I have noticed that word "Blue" is not translated into Polish (MO file) - 'pympress' displays "Blue" instead of "Niebieski". The cause is presence of "#, fuzzy" in line 237 of the locale/pl/pympress.po file  that I sent you last year. I did not remove this string (label) because I thought it is necessary. The file also contains some fuzzy entries - I am not sure if they are needed now. The same problem is probably in German translation - the presence of  "#, fuzzy" before "_Blue".

**Comment by Cimbali** [comment]
Good point. Fuzzy are translations that need to be checked because they were semi-automatically generated. I just updated a bunch of strings removing the leading "Warning: " that disappeared in English.

I still need two polish translations:
1) ["Pympress can not extract attached file"](https://github.com/Cimbali/pympress/blob/master/pympress/share/locale/pl/pympress.po#L135). The fuzzy string that is present is with media. (I'm guessing it's pliku? But I don't know a thing about declensions in Polish so I though I'd better check first).
2) ["Error opening the file"](https://github.com/Cimbali/pympress/blob/master/pympress/share/locale/pl/pympress.po#L77) Here the fuzzy string says "I can not find the file" or something like that.

**Comment by polaksta** [comment]
"media" and "plik" are synonymous words, bu "Pympress can not extract attached file", maybe  "Pympress nie może wyodrębnić osadzonego pliku" will be better translation.  In case of  "Error opening the file \"{}\"" the better translation  could be "Błąd podczas otwierania pliku \"{}\""
