### ISSUE TITLE
Gtk-WARNING for GtkPaned

### ISSUE THREAD

**Issue by FriedrichFroebel** [Cimbali/pympress#53]
### Environment
- Manjaro Linux
- Python 3.6.4

### Pympress
- version 1.1.2
- Installation method: pip

### Expected behaviour 
No warnings.

### Steps to reproduce
Run ` pympress presentation.pdf`  from the terminal - the first warning is shown. When opening the help afterwards, the second warning is shown.

### Problem
Warnings are shown:

```
(pympress:8764): Gtk-WARNING **: Allocating size to GtkPaned 0x558000273f40 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
```

**Comment by Cimbali** [comment]
Yeah the first message has been around for ages. It comes do from the way we build the UI and try to restore the pane handle positions. It originates in [`Builder.replace_layout()`](https://github.com/Cimbali/pympress/blob/master/pympress/builder.py#L233) where we recursively insert children based on the config string, then move the panel handles.

In order to set the panel handles, the `Gtk.Paned` need sizes, thus all the `queue_resize`/`show_now`/`check_resize` calls. If you remove the two last for loops from this function, the warning disappears (and Pympress won't remember where you last left your pane handle when closing the last time).

I think ideally the resizing loop shouldn't exist, and we should figure out the correct event (something like `map`, `map-event` or `realize`) that happens after size negotiation but before drawing the widget, and insert there the pane resizing (i.e. the last loop of `replace_layout`)

**Comment by Cimbali** [comment]
Turns out `size-allocate` is a good signal to do this.

**Comment by FriedrichFroebel** [comment]
Thanks for the quick fix. The warnings seem to have gone.
