### ISSUE TITLE
Zoom on selection: feature request

### ISSUE THREAD

**Issue by ceermonk** [Cimbali/pympress#66]
# Feature request

1. It would be great to have a zoom on selection feature, possibly in the highlight mode. It is useful to be able to zoom parts of a slide on the fly.

2. One suggestion regarding the highlight feature is to have the notes and current slide panes both be visible in highlight mode. That way, one can still refer to the notes while annotating the slides.

Pympress is a great presentation tool. Good work! Thank you.

**Comment by Cimbali** [comment]
Working on the zoom. I'm not sure about showing the notes with the highlights. Maybe something collapsible?

**Comment by Cimbali** [comment]
@ceermonk  if you can run from source, check out the [feature/zooming](/Cimbali/pympress/tree/feature/zooming) branch and tell me what you think.

I'm not really satisfied with the moment between the "zoom in" click and the area selection. Basically, there is no UX feedback to say "you clicked the zoom button, clicking on the slide will allow you to choose the zoomed area instead of drawing/highlighting on the slide". Maybe changing the mouse pointer is a good way of doing that?

Besides that, the main drawback is that as we pre-render slides, zooming too much gives a pixelated result. We can solve that in the future.

**Comment by ceermonk** [comment]
The zoom feature works ok. As you said, the zoomed sections are a bit pixelated, but is still useful. Thank you very much!

**Comment by Cimbali** [comment]
@ceermonk Check out the current master. Zooming is pretty now! Closing this, we'll see about notes + highlight in #67.

**Comment by ceermonk** [comment]
Zoom works perfectly! Thank you.
